#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

if [[ $EUID == 0 ]]; then
  # TODO: Check expected pitfalls first
  for plugin in git docker nginx git-apps app-long-opt \
    apps buildstep config release-env start-web-deploy \
    app-name-domain domains nginx-app-vhosts
  do
    if [[ -d "$PLUSHU_ROOT/plugins/$plugin" ]]; then
      plushu plugins:reinstall "$plugin"
    else
      plushu plugins:install "$plugin"
    fi
  done
else
  echo "You need to re-install this plugin as root."
fi
